version: '3'

services:
  api:
    container_name: chatbot-flask
    image: python:latest
    volumes:
      - ${proj_path}:/root/flask_api_demo
    working_dir: /root/flask_api_demo
    depends_on:
      - db

  db:
    container_name: chatbot-mongo
    image: mongo:latest
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_configdb:
  mongo_db:
